### ISSUE TITLE
Artists without links

### ISSUE THREAD

**Issue by tong** [verein-fuer-elektro-akustik/velak.klingt.org#13]
Currently:

adam-donovan
adam-linson
a.d.-martinz
aerom
agnes-hvizdalek
agnès-palier
ahoo-maher
ã…ke-parmerud
alain-leonard
alejandro-del-valle-lattanzio
alejandro-montes-de-oca-torres
alessandro-bosetti
alexander-chernyshkov
alexander-mairhofer
alexander-martinz
alexandr-vatagin
alice-hui-sheng-chang
allgaier
alwin-weber
amar-priganica
ambro
anders-vestergaard
andi-berger
andrea-neumann
andreas-trobollowitsch
angela-lau
anna-steiden
antonino-secchia
armando-balice
arnold-haberl
artjom
audrey-lauro
axel-dörner
ayankoko
ayonkoko
batur-sonmez
bb
be-muvi
beppu-project
bernd-klug
bernhard-gál
bernhard-hammer
bernhard-loibner
bernhard-schöberl
betancurth
bezirkshäuptling
billy-roisz
birgit-liedtke
boris-d-hegenbart
brennstein
brigitta-bödenauer
bruno-liberda
bryan-eubanks
burkhard-stangl
byron-westbrook
chieko-mori
chris-heenan
christian-friedrich
christian-müller
christian-rainer
christian-reiner
christof-kurzmann
claire-jones
claudia-cervenca
claudia-larcher
clément-vercelleto
conor-curran
continued
dafne-vicente-sandoval
damijan
daniel-lercher
daniel-mayer
dario-sanfilippo
daurer
david-grove
david-schweighart
david-seitz
dd-kern
department-pop
derek-shirley
diaf
diatribes
die-fuchteln
dieter-kaufmann
dieter-mattersdorfer
dino-spiluttini
dirac
dj-balli
dj-tommy-de-nys
dm@p
dominique-vaccaro
doris-pollhammer
eigner
elektronischer-wildschweinschutz
elffriede
elisabeth-flunger
elisabeth-hillinger
elisabeth-meilinger
els-viaene
engelsharfen
enrico-malatesta
eric-cordier
ernst-markus-stein
eugene-ignashev
evamuss-aka-chrs-galarreta
fabiana-galante
falon-cañon
federsel
fernando-perales
feron
florian-fennes
florian-haderer
florian-nastorg
florian-vanhoof
fm-einheit
francesco-cavaliere
franz-hautzinger
frederic-stritter
fumiko-nakato
gabi-teufner
gandolfo-pagano
george-bagdasarov
george-cremaschi
georg-steijskal
gerald-krist
gerhard-daurer
gerold
glim
glioksizom
gloria-damijan
gobi-drab
greg-haines
gueule-populaire
günther-auer
günther-rabl
guro-skumsnes-moe
guy-fleming
haarvard-skaset
harald-stojan
heidrun-schramm
helena-gough
helmut-kleinfercher
heribert-friedl
hernán-kerlleñevich
hong-chulki
howool-baek
hren
i8u
igor-lintz-maues
ina-jahreis
instant-reality
irena-tomazin
irene-kepl
irene-pacini
isabella-forciniti
isabelle-duthoit
izumi-ose
jacob-felix-heule
jakob-schneidewind
jan-faix
jennifer-posny
jen-paches
jerobeam-fenderson
jhidden-shards
joão-castro-pinto
johanna-forster
johannes-deutschmann
johannes-eimermacher
johann-neumeister
john-plankenhorn
joki-oberhuber
jonáš-gruska
jonas-gustafsson
jörg-piringer
juan-parra
julian-bonequi
julian-klien
julius-biswurm
juna-winston
jung-an-tagen
jym
kai-fagaschinski
kaltraum-vollmondt
kapo
karolina-jawad
katharina-arnold
katharina-ernst
katrin-hauk
kazuhisa-uchihashi
keiko-uenishi
klangküche
klaus-gstettner
klaus-janek
klaus-phillip
kollektiv-rauschen
kristen-roos
kwang
laminadyz
lars-stigler
lau-mung-leng
lawrence-casserley
léa-drouet
lee-gregory
le-mat
leo-bettinelli
leonel-kaplan
leon-naffin
lia-mazzari
lingens
liondialer
liz-allbee
lorenzo-senni
löwenstein
lucia-kagramanyan
luciano-maggiore
luis-conde
luka-ivanovic
maex-decker-bah-vs.-liii-superviced
maierhofer
maja-osojnik
mamoru
mamoru-okuno
manon-bancich
manon-bancsich
marcia-steflitsch
marcin-morga
marco-pianges
margaret-unknown
maria-chavez
marina-poleukhina
marina-vesic
marinos-koutsomichalis
mário-del-nunzio
markus-deutschmann
marta-zapparoli
martina-cizek
martin-gasser
mathias-lenz
mat-pogo
matthew-ostrowski
matthias-hafner
matthias-koch
matthias-makowsky
matthias-markovsky
max-bogner
meaghan-burke-bernd-klug
meaghan-burke
me
michaela-grill
michael-rataj
michael-renkel
michael-strohmann
michael-zacherl
misha-marks
molly-mcdolan
möström
mountain-electroacoustic-laptop-ensemble
mulian
nana-dahlin
narco-terrorism-terrestrial-analogy
neuer-aesthetik-der-tonkunst-(version-ii)
neumann
nicolas-wiese
nigel-brown
niklas-adam
nikolaus-gohm
nörz
olaf-hochherz
oliver-grimm
olivier-di-placido
olivier-toulemonde
ora-cogan
pak-yan-lau
paranoiz
patrik-redl
paula-matthusen
paul-may
pauwel-de-buck
per-salkowitsch
peter-marsh
peter-ravel-seher
peter-seher
petr-vrba
philip-leitner
philip-sollmann
pierre-borel
plenum
prszr
radu-malfatt
raymonde-iv
rehaug-themsen
reinhard-dundler
reka-kutas
réka-kutas
research-and-waves
rheuma-3000
rhsjb
richard-bruzek
ritwik-banerji
robert-gruber
robert-gruendler
robert-kellner
robert-piotrowicz
robert-schwarz
roland-panzer
roller
rosi-rehformen
rossi
rrrr
ruinu
ruse
ruse-trio
sahra-bogner
salih-dursun
sascha-neudeck
schayhan-kashemi
schoenlieb
sec
seijiro-murayama
sergio-sanchez
siegfried-friedrich
silvia-faessler
simina-badea
simon-blu-wasem
soon-io
sörés-zsolt
sorjuana-re-enacted
spillutini
stefan-brunner
stefan-heckel
stefan-kushima
stefan-löwenstein
stefan-nussbaumer
stefan-tiefengraber
stefan-voglsinger
steffi-neuhuber
sw_90120
sweet-spot
takashi-makino
taku-hanoda
tamara-friebel
taro
tetsuya-hori
tetsuya-umeda
teufelsgeigen
the-midi-mind-bend
thomas-berghammer
thomas-grill
thomas-grimm
thomas-havlik
thomas-tilly
tomás-cabado
tomasi
tony-dryer
torùn.-grisi-weikinger
trans-human
tr
tring-tse
ulrich-rois
valeri-ebm
vanessa-arn
vehlharkophonisches-pfingstoratorium
velharmonisches-orchester
verena-dürr
victor-halbnarr
vj-azz
volkmar-klien
weiping-lin
wei-ya-lin
wendy
william-bilwa-costa
wolfgang-fuchs
wolfgang-musil
xavier-lopez
xavier-weydert
yanjiu-er
yannick-franck
yellowknives
yuji-ishihara
zahaikevych-misto
z.b.
zen-lu
zlanabitnig
zo-on-slows
zoro-babel

**Comment by trbgt** [comment]
i know that some of these people have websites but i think its a bit of an overkill so search for websites of people. in the future we will try to add a link (if available) for every person playing. and some just wont have a link to their HP which i think its alright

**Comment by tong** [comment]
ok.
