### ISSUE TITLE
Broken `A` when using Inter font on macos

### ISSUE THREAD

**Issue by tong** [verein-fuer-elektro-akustik/velak.klingt.org#5]
The capital `A` character is broken when using the Inter font as woff2 on macos.  

<img width="364" alt="bildschirmfoto_2022-08-09_um_14 54 15" src="https://user-images.githubusercontent.com/203646/183654861-b6cc0133-d809-403b-9f6c-05aa5b32492f.png">

It works when loading from fonts.google but fuck google.

**Comment by tong** [comment]
Loading woff file seems to work.

**Comment by markusmayerroth** [comment]
As suspected the A consists of two overlapping shapes which may be interpreted in different ways …
<img width="652" alt="Bildschirmfoto 2022-08-31 um 13 26 28" src="https://user-images.githubusercontent.com/2905431/187668156-b3c7cc3e-b22c-4b46-9a86-118de402366e.png">

**Comment by markusmayerroth** [comment]
Should theoretically also be a problem with Q or f for instance …

**Comment by markusmayerroth** [comment]
Couldn’t reproduce on macOS 12.5.1 / Safari 15.6.1
<img width="1369" alt="Bildschirmfoto 2022-08-31 um 13 36 19" src="https://user-images.githubusercontent.com/2905431/187669701-fafbedab-a9a9-4c57-88a8-ae22eb139f33.png">

**Comment by tong** [comment]
that's because it loads the woff file only (not woff2).

**Comment by tong** [comment]
The font author loads the _variable_ version: https://rsms.me/inter/
.. which seems to work.
Would be another workaround.
Though i don't know if variable fonts are supported in all browsers.

**Comment by tong** [comment]
Inter v4.0 got released.  
Test if this solves the fuckup.
