### ISSUE TITLE
gala88/89 data mix

### ISSUE THREAD

**Issue by tong** [verein-fuer-elektro-akustik/velak.klingt.org#8]
There is confusing data for gala#88, gala89.

gala#88 is missing at [velak.klingt.org](https://velak.klingt.org/), but the brut website has an [entry](https://brut-wien.at/en/Programme/Calendar/Programme-2016/2016_03_Maerz-2016/2016_03_imagetanz_Velak-Gala) claiming it's the 88th gala edition, but with the same data as gala#89 on velak.klingt.org.

not sure what is right/wrong.  
any ideas?

**Comment by trbgt** [comment]
no ideas. maybe one of the export before or after where labeld/counted as gala #88 and the person who organized the next event thought the export before was the 88th and continued with 89??
anyways... 88 is not a nice number anyways;) is it possible to just leave it out? a little mistery  on the velak paga so to say

**Comment by trbgt** [comment]
also for this i will ask vinzenz if he knows remembers what was going pn with the gala88

**Comment by trbgt** [comment]
so there was no gala 88 :)
i hope this doesnt make any problems with programming the page

**Comment by tong** [comment]
no prob.
